### PR TITLE
Replace TensorRT deperecated function

### PR DESCRIPTION
**Pull request by fateshelled**
Replace TensorRT deprecated function and minor fix.

### CODE REVIEW

**Comment by Ar-Ray-code** [comment]
Thank you for your contribution.
Please share your CUDA & TensorRT environment for my testing🙏

**Comment by fateshelled** [comment]
I'm tested CUDA 11.8 & TensorRT 8.6.1 on WSL2.

**Comment by fateshelled** [comment]
Fix CMakeLists.txt.
and I have also confirmed that it works in CUDA12.4 and TensorRT 10.1 on Ubuntu22.04.

**Comment by Ar-Ray-code** [comment]
LGTM. I'll update the dockerfile to the latest version.

**Pull request merged**
